# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Unet2D": "00_core.ipynb",
         "weighted_softmax_cross_entropy": "00_core.ipynb",
         "zero_loss": "00_core.ipynb",
         "IoU": "03_metrics.ipynb"}

modules = ["unet.py",
           "metrics.py"]

doc_url = "https://matjesg.github.io/deepflash2/"

git_url = "https://github.com/matjesg/deepflash2/tree/master/"

def custom_doc_links(name): return None
