# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Learner.apply_dropout": "00_learner.ipynb",
         "Learner.predict_tiles": "00_learner.ipynb",
         "UNetConvBlock": "01_models.ipynb",
         "UNetUpBlock": "01_models.ipynb",
         "UNet2D": "01_models.ipynb",
         "unet_ronneberger2015": "01_models.ipynb",
         "unet_falk2019": "01_models.ipynb",
         "unet_deepflash2": "01_models.ipynb",
         "unet_custom": "01_models.ipynb",
         "show": "02_data.ipynb",
         "calculate_weights": "02_data.ipynb",
         "DeformationField": "02_data.ipynb",
         "RandomTileDataset": "02_data.ipynb",
         "TileDataset": "02_data.ipynb",
         "Dice_f1": "03_metrics.ipynb",
         "Iou": "03_metrics.ipynb",
         "Recorder.plot_metrics": "03_metrics.ipynb",
         "ElasticDeformCallback": "04_callbacks.ipynb",
         "WeightedSoftmaxCrossEntropy": "05_losses.ipynb",
         "unzip": "06_utils.ipynb",
         "ensemble_results": "06_utils.ipynb",
         "plot_results": "06_utils.ipynb",
         "iou": "06_utils.ipynb",
         "label_mask": "06_utils.ipynb",
         "get_candidates": "06_utils.ipynb",
         "iou_mapping": "06_utils.ipynb",
         "calculate_roi_measures": "06_utils.ipynb",
         "calc_iterations": "06_utils.ipynb"}

modules = ["learner.py",
           "models.py",
           "data.py",
           "metrics.py",
           "callbacks.py",
           "losses.py",
           "utils.py"]

doc_url = "https://matjesg.github.io/deepflash2/"

git_url = "https://github.com/matjesg/deepflash2/tree/master/"

def custom_doc_links(name): return None
