# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_callbacks.ipynb (unless otherwise specified).

__all__ = ['ElasticDeformCallback']

# Cell
from fastai.callback.core import Callback

# Cell
class ElasticDeformCallback(Callback):
    "`Callback` that recomputes elastic deformations after each epoch"
    run_valid = False
    def after_epoch(self):
        "Randomly recompute elastic deformations"
        self.learn.dls.train.on_epoch_end()