# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_metrics.ipynb (unless otherwise specified).

__all__ = ['Dice_f1', 'Iou']

# Cell
from fastai2.metrics import Dice

# Cell
class Dice_f1(Dice):
    "Dice coefficient metric for binary target in segmentation"
    def accumulate(self, learn):
        pred,targ = flatten_check(learn.pred.argmax(dim=self.axis), learn.y[0].argmax(dim=self.axis))
        self.inter += (pred*targ).float().sum().item()
        self.union += (pred+targ).float().sum().item()

# Cell
class Iou(Dice_f1):
    "Implemetation of the IoU (jaccard coefficient) that is lighter in RAM"
    @property
    def value(self): return self.inter/(self.union-self.inter) if self.union > 0 else None